// Data store for Báo Cáo Inbound VN
// All entities are linkable — ids matter.

window.DATA = {

  halongHub: {
    id: 'halong-hub',
    name: 'Cruise Vịnh Hạ Long',
    isHub: true,
    market: {
      gmv2025: '$580–680M',
      guests2025: '4.0–4.5M',
      cruiseSharePct: '38–42%',
      operators: '180–220',
      growthCAGR: '+12–15%',
      gmv2028base: '$900M–1.08B',
    },
    seasonality: [
      { id: 1,  short: 'T1',  index: 80  },
      { id: 2,  short: 'T2',  index: 65  },
      { id: 3,  short: 'T3',  index: 100 },
      { id: 4,  short: 'T4',  index: 135 },
      { id: 5,  short: 'T5',  index: 130 },
      { id: 6,  short: 'T6',  index: 140 },
      { id: 7,  short: 'T7',  index: 145 },
      { id: 8,  short: 'T8',  index: 125 },
      { id: 9,  short: 'T9',  index: 110 },
      { id: 10, short: 'T10', index: 135 },
      { id: 11, short: 'T11', index: 120 },
      { id: 12, short: 'T12', index: 95  },
    ],
    variants: [
      {
        name: 'Day Cruise 6–8h',
        price: '$45–85',
        segment: 'Budget',
        share: '45–50% lượt đặt · 20–25% GMV',
        markets: ['cn', '🇨🇳', '🇻🇳'],
        topComp: { name: 'Halong Seasun Day', reviews: '3,000–5,000+', rating: 4.4, price: '$38–65' },
        compStrength: 'Giá tốt, lunch included, nhiều departure trong ngày',
        compGap: 'Tàu đông, không kayak hang sâu, guide chất lượng không đều',
        emerging: false,
      },
      {
        name: 'Overnight Standard 1N2D',
        price: '$180–280',
        segment: 'Mid',
        share: '30–35% lượt đặt · 35–40% GMV',
        markets: ['🇰🇷', '🇮🇳', '🇹🇼'],
        topComp: { name: 'Bhaya Classic Overnight', reviews: '1,500–2,500+', rating: 4.5, price: '$280–450' },
        compStrength: 'Tàu truyền thống, hải sản tươi, OTA phủ rộng GYG + Booking',
        compGap: 'Tàu >15 năm, cabin ồn, menu F&B lặp lại, guide tiếng Anh không đều',
        emerging: false,
      },
      {
        name: 'Premium 2N3D',
        price: '$500–900',
        segment: 'Premium',
        share: '12–15% lượt đặt · 25–30% GMV',
        markets: ['🇺🇸', '🇦🇺', '🇬🇧'],
        topComp: { name: 'Paradise Elegance 2N3D', reviews: '1,200–2,000+', rating: 4.8, price: '$850–1,400' },
        compStrength: 'Brand equity cao nhất thị trường, spa + balcony, đội ngũ chuyên nghiệp',
        compGap: '30+ cabin = vẫn đông giờ cao điểm, giá khó tiếp cận mid-budget, TikTok presence yếu',
        emerging: false,
      },
      {
        name: 'Lan Hạ Bay Route',
        price: '$200–400',
        segment: 'Mid-Premium',
        share: 'Đang tăng nhanh 2025–2026',
        markets: ['🇺🇸', '🇦🇺', '🇬🇧'],
        topComp: { name: 'Indochina Sails Lan Ha', reviews: '2,500–4,000+', rating: 4.6, price: '$300–550' },
        compStrength: 'Route phong phú nhất, Bái Tử Long add-on, 3-day tour popular',
        compGap: 'Tàu đang nâng cấp, F&B dưới Paradise, direct booking yếu',
        emerging: true,
        emergingNote: 'Khách tìm "ít đông hơn Hạ Long chính" — kayak cave đẹp hơn, ít UNESCO tourist trap',
      },
      {
        name: 'Luxury Private 3N4D+',
        price: '$1,200–2,400+',
        segment: 'Luxury',
        share: '3–5% lượt · 12–18% GMV',
        markets: ['🇺🇸', '🇬🇧', '🇦🇺'],
        topComp: { name: 'Heritage Binh Chuan', reviews: '600–1,100+', rating: 4.9, price: '$1,300–2,200' },
        compStrength: 'Art deco độc đáo, NPS cao nhất thị trường, ultra-exclusive 20 cabin',
        compGap: 'Chỉ 1 tàu = hard to book, giá cực cao, không OTA → limited reach',
        emerging: false,
      },
      {
        name: 'Seaplane Combo',
        price: '$400–800',
        segment: 'Premium',
        share: '<2% hiện tại — đang tăng',
        markets: ['🇺🇸', '🇦🇺'],
        topComp: { name: 'Thien Minh + Seaplane', reviews: 'N/A', rating: null, price: '$500–900' },
        compStrength: 'View từ trên không độc nhất, TikTok viral 2025',
        compGap: 'Phụ thuộc thời tiết, ít operator làm được, giá cao',
        emerging: true,
        emergingNote: 'TikTok "Ha Long seaplane" >50M views · ADR tăng 35% YoY · window 2026–2027',
      },
    ],
    topCompetitors: [
      {
        name: 'Paradise Group',
        tier: 'Luxury',
        ships: '8 tàu · 150+ cabin',
        reviews: '3,500–5,500+',
        rating: 4.8,
        priceRange: '$850–1,400/cặp 2N3D',
        channelMix: 'Direct 40% · Booking.com 25% · B2B 20%',
        strengths: ['Brand equity cao nhất — khách tự tìm đến', 'Đội ngũ chuyên nghiệp nhất thị trường', 'Spa đầy đủ, balcony, tàu đẹp', 'Fleet 8 tàu — flexibility cao'],
        gaps: ['Tàu 30+ cabin = đông giờ kayak cao điểm', 'Giá quá cao cho mid-budget ($850+ cặp)', 'TikTok/social presence yếu', 'Phụ thuộc brand sẵn có — khó copy model'],
        opp: 'Gap $400–700/cặp chưa ai fill tốt giữa Standard và Paradise. Khách muốn chất lượng cao nhưng không trả giá luxury.',
      },
      {
        name: 'Heritage Binh Chuan',
        tier: 'Ultra-Luxury',
        ships: '1 tàu · 20 cabin',
        reviews: '600–1,100+',
        rating: 4.9,
        priceRange: '$1,300–2,200/cặp 2N3D',
        channelMix: 'Direct 50% · Luxury agents 35%',
        strengths: ['NPS cao nhất thị trường', 'Art deco độc đáo — positioning rõ ràng nhất', 'Ultra-exclusive 20 cabin — không bao giờ đông', 'F&B đẳng cấp — executive chef'],
        gaps: ['Chỉ 1 tàu — không scale được', 'Giá cực cao → rào cản lớn', 'Không OTA → chỉ reach khách đã biết brand', 'Không có budget hoặc day option'],
        opp: '"Private feel" của Heritage có thể democratize ở $400–700 — 20 cabin + storytelling mạnh mà không cần ultra-luxury capex.',
      },
      {
        name: 'Essence Grand / Era Cruises',
        tier: 'Premium',
        ships: '3 tàu · 65 cabin',
        reviews: '800–1,500+',
        rating: 4.7,
        priceRange: '$420–680/cặp 2D1N',
        channelMix: 'GYG 30% · Klook 25% · Viator 20% · Direct 10%',
        strengths: ['Tàu MỚI 2023–2024 — cabin đẹp nhất hiện tại', 'Social media mạnh, TikTok presence tốt', 'OTA phủ rộng GYG+Klook+Viator', 'Thiết kế trẻ trung, hút Millennial'],
        gaps: ['Brand chưa có equity — phụ thuộc OTA ranking hoàn toàn', 'Review count còn thấp vs Bhaya/Paradise', 'Chưa có B2B/MICE channel', 'Direct booking <10% — commission drag cao nhất nhóm'],
        opp: 'Competitor dễ beat nhất về brand story và direct booking. Nếu đầu tư content + CRM trước họ, có thể lấy search share trong 6–12 tháng.',
      },
    ],
    otaByMarket: [
      { market: 'Mỹ 🇺🇸',     booking: 2, agoda: 1, gyg: 4, klook: 1, viator: 5, direct: 3 },
      { market: 'Úc 🇦🇺',     booking: 3, agoda: 1, gyg: 4, klook: 1, viator: 4, direct: 3 },
      { market: 'Anh 🇬🇧',    booking: 3, agoda: 1, gyg: 5, klook: 1, viator: 3, direct: 2 },
      { market: 'Hàn 🇰🇷',    booking: 3, agoda: 4, gyg: 2, klook: 5, viator: 1, direct: 1 },
      { market: 'Ấn Độ 🇮🇳',  booking: 2, agoda: 3, gyg: 2, klook: 3, viator: 1, direct: 1 },
      { market: 'Trung 🇨🇳',  booking: 2, agoda: 4, gyg: 1, klook: 3, viator: 1, direct: 2 },
      { market: 'Pháp 🇫🇷',   booking: 4, agoda: 1, gyg: 5, klook: 1, viator: 3, direct: 2 },
      { market: 'Nội địa 🇻🇳', booking: 1, agoda: 2, gyg: 1, klook: 2, viator: 1, direct: 3 },
    ],
    painPoints: [
      { rank: 1, pain: 'Tàu quá đông, chen chúc giờ kayak', freq: '40–55%', sev: 5, opp: 'Tàu nhỏ 8–20 cabin hoặc exclusive itinerary', positioning: '"The Private Bay Experience"' },
      { rank: 2, pain: 'F&B chất lượng kém / menu lặp', freq: '35–45%', sev: 4, opp: 'Chef-driven menu theo mùa + cooking class', positioning: '"Michelin-inspired onboard dining"' },
      { rank: 3, pain: 'Hoạt động bị cắt/rút ngắn không báo', freq: '28–38%', sev: 5, opp: 'Transparent comms + compensation policy', positioning: '"100% itinerary or compensation"' },
      { rank: 4, pain: 'Hidden fees (transfer, kayak, drinks)', freq: '25–35%', sev: 4, opp: 'All-inclusive pricing công khai', positioning: '"What you see is what you pay"' },
      { rank: 5, pain: 'Guide tiếng Anh kém / thiếu chiều sâu', freq: '20–30%', sev: 4, opp: 'Guide fluent + cultural storytelling training', positioning: '"Stories, not scripts"' },
      { rank: 6, pain: 'Cabin bé / ồn / tiếng động cơ', freq: '25–35%', sev: 4, opp: 'Cabin mới, cách âm tốt', positioning: 'Premium cabin tier' },
      { rank: 7, pain: 'Upsell aggressive trên tàu', freq: '18–28%', sev: 3, opp: 'Pre-cruise bundle 1 lần, không làm phiền trên tàu', positioning: '"No pushy sales onboard"' },
    ],
    trends: [
      { name: 'Private / Exclusive', impact: 5, stars: '★★★★★', peak: '2026–2028', note: 'ADR tier này $350→$480→$650 — demand vượt supply. Top 8–12 tàu đang thu 28–35% GMV toàn thị trường.' },
      { name: 'TikTok / IG Content-first', impact: 5, stars: '★★★★★', peak: '2025–2027', note: '"Halong Bay cruise" >2.5B TikTok views. Jacuzzi trên boong, kayak hang, bữa sáng trong cave = signature moments bắt buộc.' },
      { name: 'Digital Detox & Wellness', impact: 4, stars: '★★★★☆', peak: '2026–2027', note: '15–20% khách cao cấp trả thêm $40–80/đêm cho yoga/spa cruise. Tai chi sunrise review nhiều nhất.' },
      { name: 'Lan Hạ / Bái Tử Long mở rộng', impact: 4, stars: '★★★★☆', peak: '2026–2027', note: 'Search "Lan Ha Bay cruise" tăng 45% YoY. Khách tìm trải nghiệm "ít đông" — route mới đang thắng trong OTA search.' },
      { name: 'Sustainable / Green', impact: 4, stars: '★★★★☆', peak: '2027–2029', note: 'UNESCO deadline 2030: 50% tàu phải đạt chuẩn xử lý nước thải. Operator đầu tư sớm có lợi thế PR + giấy phép.' },
      { name: 'Coffee-to-Cruise Bundle', impact: 4, stars: '★★★★☆', peak: '2026', note: 'Cross-sell cruise + workshop HN. Bundle booking tăng 35–45%/năm trên GYG/Klook. Incremental $80K–180K/năm cho operator mid-size.' },
      { name: 'AI Booking & Personalization', impact: 3, stars: '★★★☆☆', peak: '2026–2028', note: 'Smart chatbot + dynamic pricing tăng direct conversion 20–30%. GYG/Klook đang triển khai AI recommendation.' },
    ],
    designLevers: [
      { market: 'Mỹ 🇺🇸', type: 'Couple/Family 40–55', lever: 'Cultural storytelling sâu về ngư dân, lịch sử vịnh. Sunset private dinner. Flexible itinerary. Cancellation policy rõ ràng.', impact: '+$40–80/người' },
      { market: 'Úc 🇦🇺', type: 'Couple/Adventure 35–55', lever: 'Small group <20 pax. Kayak hang sâu, squid fishing đêm, tai chi sunrise. Guide kể chuyện thật, không script.', impact: '+$30–60/người' },
      { market: 'Anh 🇬🇧', type: '2 nhóm: couple 45+ và gap-year 18–22', lever: 'Couple: boutique cabin + gin sundowner + authentic story. Gap-year: last-minute flexible booking + budget-friendly private cabin.', impact: 'Hai tier giá riêng' },
      { market: 'Hàn 🇰🇷', type: 'Couple + nhóm 25–40', lever: 'Jacuzzi boong photo-worthy, BBQ đêm, Korean music option, TikTok "wow moment" rõ ràng. Klook flash sale tháng 6–8.', impact: '+$25–50/người' },
      { market: 'Ấn Độ 🇮🇳', type: 'Gia đình mở rộng 6–10 người', lever: 'Family room 3–4 người. Jain/vegetarian menu. Guide Hindi+English. Group rate cho 6+ pax. MakeMyTrip bundle.', impact: 'Volume tăng 40%' },
    ],
  },

  months: [
    {
      id: 1, name: 'Tháng 1', short: 'T1', hasData: true,
      phase: { mode: 'execute', label: 'Execute tháng này', sub: 'Khách đã book từ Oct–Nov. Tập trung delivery + review. Đồng thời: Book cho T3 (spring break) đang mở.' },
      headline: 'Mùa đỉnh nối tiếp — Giáng Sinh vừa qua nhưng khách Mỹ, Úc, Anh vẫn đang trên đường.',
      sub: 'Thời tiết hoàn hảo toàn quốc — đây là tháng để thu review và fill slot; Tết 2025 rơi vào 29/1 (tuần cuối tháng) nên phải brief khách sớm về vendor schedule.',
      featuredTours: ['india-halong', 'hanoi-food-night', 'hoi-an-wellness', 'bana-hills'],
      featuredMarkets: ['us', 'au', 'uk', 'ca'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Đỉnh mùa khô', note: '20–25°C, ít mưa (~50mm/tháng) — tốt nhất trong năm' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Push mạnh', note: 'Ấm khô, Mekong bình thường, Đà Lạt mát mẻ' },
        { region: 'Sapa / Hà Giang', status: 'yellow', label: 'Cẩn thận', note: 'Sương mù dày, rét đậm (5–10°C), có thể có tuyết — tầm nhìn kém' },
        { region: 'Hà Nội', status: 'green', label: 'Push mạnh', note: 'Cool dry 15–20°C, lý tưởng đi bộ và food tour buổi tối' },
        { region: 'Phú Quốc', status: 'green', label: 'Push mạnh', note: 'Mùa khô đẹp, biển xanh, nắng ổn định' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Push mạnh', note: 'Biển êm, mát mẻ — window tốt nhất trong năm cho cruise' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 40, gyg: 20, klook: 15, makemytrip: 8, direct: 17 },
      summary: { totalBookings: '~42,000', vsLastYear: '+8%', avgStay: '9 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'viator', reason: 'Traffic US/UK/AU đang peak. Optimize Viator listing với ảnh winter sunshine Hội An và tag "New Year escape". Direct channel (17%) cao bất thường — push email tới repeat clients.' },
      pullquote: 'Tháng 1 — thời tiết hoàn hảo, khách đã đặt từ tháng 10; nhiệm vụ không phải bán thêm mà đừng để trống slot bằng cách quên brief khách về Tết 29/1.',
      insight: {
        opp: 'Booking tháng 1 hầu hết đã chốt từ Sep–Oct — đây là tháng để chạy, không phải để sell mới. Tập trung vào experience quality, collect review 5 sao, và dùng tháng này để test listing optimization cho Jul–Aug. Halong cruise tháng 1 có window tốt nhất năm — upsell lên premium tier (overnight vs day trip).',
        risk: 'Tết 2025 = 29/1 — vendor, restaurant, guide về quê từ khoảng 27/1; đóng cửa 5–7 ngày đến 2–3/2. Phải brief khách về Tết schedule và chuẩn bị plan B cho tour food tuần cuối tháng. Xác nhận guide availability cho tất cả booking tuần 27/1–2/2 ngay bây giờ.',
      },
    },
    {
      id: 2, name: 'Tháng 2', short: 'T2', hasData: true,
      phase: { mode: 'execute', label: 'Post-Tết recovery + Execute', sub: 'Tết 2025 đã qua 29/1. Ops phục hồi từ ~5/2. UK half-term 17–21/2 là spike chính. Đồng thời: book T4–T5.' },
      headline: 'UK half-term kéo spike ngắn — Tết đã qua từ 29/1, tháng 2 là tháng phục hồi ops và push premium cruise.',
      sub: 'Post-Tết recovery từ ~5/2: vendor, guide, restaurant hoạt động trở lại bình thường. Thời tiết đỉnh miền Bắc và Trung, cruise season vẫn mạnh — cơ hội sell premium cho thị trường Anh và Úc đang cao điểm.',
      featuredTours: ['hoi-an-wellness', 'india-halong', 'hanoi-food-night'],
      featuredMarkets: ['uk', 'au', 'us', 'nz'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Tốt nhất năm', note: '21–25°C, dry — đỉnh điểm mùa du lịch Miền Trung' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Push mạnh', note: 'Warm dry, Đà Lạt mát mẻ, Mekong ổn định' },
        { region: 'Sapa / Hà Giang', status: 'yellow', label: 'Cẩn thận', note: 'Sương mù + rét đậm đầu tháng; ấm dần cuối tháng' },
        { region: 'Hà Nội', status: 'green', label: 'Push mạnh', note: 'Cool dry 16–20°C — tháng đẹp nhất cho Hanoi walking tour' },
        { region: 'Phú Quốc', status: 'green', label: 'Push mạnh', note: 'Peak mùa khô, biển xanh, nắng ổn định' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Push mạnh', note: 'Cruise window mạnh — biển êm sau Tết' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 38, gyg: 22, klook: 14, makemytrip: 9, direct: 17 },
      summary: { totalBookings: '~38,000', vsLastYear: '+11%', avgStay: '8 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'gyg', reason: 'UK half-term (17–21/2) là spike ngắn nhưng GYG mạnh nhất traffic Anh. Viator vẫn chủ lực. Direct 17% — khách cũ book thẳng sau khi ops ổn định hậu Tết.' },
      pullquote: 'Tháng 2 — Tết vừa qua, thời tiết đạt đỉnh, UK half-term bắt đầu 17/2; 3 tuần đầu tháng là cơ hội bán hàng không cần ads, chỉ cần ops chạy đúng.',
      insight: {
        opp: 'UK half-term (17–21/2) tạo spike 7–10 ngày — nhỏ về volume nhưng cao về chi tiêu (gia đình Anh average $250–400/ngày). Tháng 2 cũng là tháng tốt nhất để push Hoi An Wellness và walking vì thời tiết Miền Trung đạt đỉnh (21–25°C, không mưa, golden light). Cruise premium tier (Paradise Elegance, Emperor) có fill rate tốt — upsell từ overnight lên 3D2N.',
        risk: 'Post-Tết 2025 (29/1) — các operation có thể bị delay đầu tháng 2 (tuần 3–9/2 là giai đoạn vendor phục hồi dần). Confirm với tất cả guide và restaurant partner rằng họ đã mở cửa đầy đủ trước khi confirm UK half-term bookings. Direct channel (17%) cao — nurture repeat clients từ nhóm khách vừa trải nghiệm Tết.',
      },
    },
    {
      id: 3, name: 'Tháng 3', short: 'T3', hasData: true,
      phase: { mode: 'book', label: 'Book tháng này + Execute spring break', sub: 'US spring break đang travel. Song song: đây là cửa sổ book T6–T7 — optimize Viator listing ngay để capture summer search.' },
      headline: 'Mỹ spring break kéo gia đình — thời tiết Miền Trung vẫn còn window tốt trước khi chuyển mùa.',
      sub: 'Shoulder season nhưng volume từ US spring break và AU/NZ đủ để justify listing push — AU và NZ còn trong Term 1 tháng 3, autumn break bắt đầu đầu tháng 4.',
      featuredTours: ['india-halong', 'ha-giang-jeep', 'hoi-an-wellness', 'hanoi-food-night', 'mekong-delta'],
      featuredMarkets: ['us', 'au', 'nz'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Tốt — dry tail', note: '24–27°C, cuối mùa khô, vẫn đẹp' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Push mạnh', note: 'Dry season còn đó, nóng 30–33°C — push sáng sớm / tối, Đà Lạt mát hơn' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Push mạnh', note: 'Hoa đào/mận nở, min 17°C — đẹp nhất trước mùa mưa tháng 4–5' },
        { region: 'Hà Nội', status: 'green', label: 'Push mạnh', note: '17–25°C, nồm ẩm / drizzle nhẹ đặc trưng tháng 3 — vẫn OK' },
        { region: 'Phú Quốc', status: 'green', label: 'Tốt', note: 'Cuối mùa khô, biển vẫn tốt trước khi gió đổi' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Push mạnh', note: 'Tốt — cruise season vẫn chạy mạnh' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 42, gyg: 18, klook: 17, makemytrip: 7, direct: 16 },
      summary: { totalBookings: '~56,000', vsLastYear: '+14%', avgStay: '10 ngày', topRegion: 'Miền Bắc + Nam' },
      otaRec: { ota: 'viator', reason: 'US spring break = Viator dominant. Klook 17% cao hơn bình thường vì Singapore/NZ leg. Đây là tháng optimize Viator listing cho T6–T7 — search volume summer đang tăng.' },
      pullquote: 'Spring break Mỹ chỉ có 3 tuần — operator nào optimize listing trước ngày 1 tháng 3 sẽ ăn hết slot, còn lại chỉ nhặt thừa.',
      insight: {
        opp: 'Spring break Mỹ chỉ kéo dài 3 tuần — window hẹp nhưng predictable. Gia đình US book tour full-day hoặc combo (Cu Chi+Mekong, Halong cruise, Hoi An) với budget $150–300/người. Listing optimize tháng 1–2 để capture March search. Halong cruise tháng 3 còn tốt trước khi bão mùa hè — push overnight tier.',
        risk: 'Thời tiết Miền Trung đang ở cuối dry season — book tour Hội An cho tháng 3 an toàn, nhưng đừng sell tour outdoor Đà Nẵng quá xa vào cuối March khi transition bắt đầu. AU/NZ vẫn đang trong school term tháng 3 — autumn break chỉ bắt đầu đầu April (VIC ~4/4, NSW ~11/4). Review cancellation policy cho listings tháng 4 trở đi.',
      },
    },
    {
      id: 4, name: 'Tháng 4', short: 'T4', hasData: true,
      phase: { mode: 'book', label: 'Book T5–T7 + Execute shoulder', sub: 'AU/NZ autumn break đang travel. Đây là window book guide Ha Giang cho T7 — slot tốt sẽ hết trước T6.' },
      headline: 'AU/NZ autumn break đổ khách — Easter Anh kéo gia đình ra và Philippines summer mở; tháng 4 có nhiều hơn những gì vẻ ngoài.',
      sub: 'Easter UK school holiday (7–22/4) + ANZAC Day 25/4 + Úc/NZ autumn break đầu tháng — shoulder có thật nhưng demand đến từ nhiều trigger cùng lúc, cần channel đúng.',
      featuredTours: ['ha-giang-jeep', 'bana-hills', 'hoi-an-wellness', 'phu-quoc-snorkel'],
      featuredMarkets: ['uk', 'au', 'nz', 'ph'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'yellow', label: 'Chuyển mùa', note: 'Mưa nhẹ bắt đầu cuối tháng, vẫn đi được đầu T4' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'yellow', label: 'Nóng', note: 'Pre-monsoon 32–35°C — push Đà Lạt thay HCMC' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Push mạnh', note: 'Trước mùa mưa, đường đẹp, chưa nguy hiểm' },
        { region: 'Hà Nội', status: 'yellow', label: 'Cẩn thận', note: '22–27°C ẩm, mưa xuân còn đó — push evening tours' },
        { region: 'Phú Quốc', status: 'green', label: 'Tốt', note: 'Cuối mùa khô — window cuối trước gió Tây tháng 5' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Tốt', note: 'OK trước khi typhoon risk xuất hiện tháng 7–8' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 35, gyg: 19, klook: 26, makemytrip: 8, direct: 12 },
      summary: { totalBookings: '~48,000', vsLastYear: '+9%', avgStay: '9 ngày', topRegion: 'Miền Bắc + Nam' },
      otaRec: { ota: 'klook', reason: 'Klook 26% cao nhất T4 — Philippines summer traffic bắt đầu từ 15/4 và Klook là sàn chính của PH/SG. Viator vẫn quan trọng cho UK Easter. Optimize Klook listing "Easter Vietnam" và "Philippines Summer" ngay.' },
      pullquote: 'Tháng 4 không phải tháng để bán — là tháng để plan. Ai book guide Ha Giang cho tháng 7 từ bây giờ mới có slot, ai đợi tháng 6 thì chỉ còn nhặt thừa.',
      insight: {
        opp: 'Tháng 4 là advance booking window cho T5–T7. Klook PH cần optimize ngay để capture Philippines summer traffic (từ 15/4). Phú Quốc có window cuối mùa khô ngắn trước gió Tây tháng 5 — upsell beach trip cho khách muốn biển trước khi hết mùa. Ha Giang tháng 4 vẫn đẹp và an toàn — capture AU/NZ autumn break (VIC ~4/4–18/4, NSW ~11/4–25/4) với jeep tour.',
        risk: 'Shoulder thật sự về volume — đừng kỳ vọng T7 volume. Dùng tháng 4 để prepare: book guide Ha Giang cho tháng 7 (slot tốt đang được đặt), update listing hero image cho mùa hè (lúa xanh, Da Nang beach), setup Klook PH merchant nếu chưa có.',
      },
    },
    {
      id: 5, name: 'Tháng 5', short: 'T5', hasData: true,
      phase: { mode: 'book', label: 'Book T7–T8 + Execute Asia peak', sub: 'India summer và PH peak đang travel. Song song: đây là window book slot T7 — Viator listing cho peak hè phải sẵn từ tháng 5.' },
      headline: 'Ấn Độ mùa hè bắt đầu, Đà Nẵng vào mùa khô đỉnh — hai cơ hội lớn mà phần lớn operator VN bỏ qua.',
      sub: 'DIFF khai mạc đêm 31/5; Central Coast DRY season tốt nhất năm trong khi miền Bắc đã vào mưa — đây là messaging gap lớn nhất để khai thác.',
      featuredTours: ['bana-hills', 'ha-giang-jeep', 'india-halong', 'hoi-an-wellness'],
      featuredMarkets: ['in', 'ph', 'sg', 'us'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Đỉnh mùa khô', note: 'DRY SEASON bắt đầu May–Aug — ít mưa nhất trong năm, lợi thế vs Bắc' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Tốt', note: 'Pre-monsoon vẫn manageable; Đà Lạt mát quanh năm' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Push mạnh', note: 'Rice planting season — ruộng bậc thang đổ nước, ảnh mirror đẹp' },
        { region: 'Hà Nội', status: 'green', label: 'Tốt', note: 'Best May–Jun trước Jul–Aug nóng cực đoan' },
        { region: 'Phú Quốc', status: 'yellow', label: 'Cẩn thận', note: 'Gió Tây bắt đầu tháng 5 — transition sang monsoon' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Tốt', note: 'Còn OK trước khi typhoon risk xuất hiện Jul–Aug' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 28, gyg: 14, klook: 30, makemytrip: 20, direct: 8 },
      summary: { totalBookings: '~68,000', vsLastYear: '+16%', avgStay: '10 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'klook', reason: 'Klook 30% + MakeMyTrip 20% = 50% thị phần tháng 5 từ Asian markets. Optimize MakeMyTrip listing tiếng Anh rõ ràng cho India summer. Thêm "Dry Season May–August" vào title listing Đà Nẵng/Hội An để capture India/PH search.' },
      pullquote: 'Tháng 5 — Central Coast đang không có mưa trong khi Hà Nội đã bắt đầu. Đó là câu bán hàng bạn nên dùng nhưng listing của bạn chưa nói ra.',
      insight: {
        opp: 'Central Coast DRY SEASON bắt đầu tháng 5 trong khi Hà Nội và Sapa đang vào mưa — đây là thông tin mà 80% du khách không biết. Listing title Da Nang/Hoi An phải thêm "Dry Season May–August" ngay để capture search từ India và Philippines đang book. DIFF opening đêm 31/5 + Hoi An day là combo bán được ngay không cần sáng tạo thêm. CBSE India summer holiday từ ~26/4 — MakeMyTrip traffic đang peak ngay tháng 5.',
        risk: 'MakeMyTrip thị phần 20% — cao nhất trong năm (India summer peak). Optimize listing tiếng Anh rõ ràng, không dùng jargon địa phương (tên phố VN, từ chỉ dùng trong nước). Phú Quốc: tắt promotion beach tours ngay tháng 5, chuyển budget sang Central Coast. Philippines summer kết thúc 15/6 — capture PH traffic trong May trước khi school khai giảng 16/6.',
      },
    },
    {
      id: 6, name: 'Tháng 6', short: 'T6', hasData: true,
      phase: { mode: 'execute', label: 'Execute — Asian market peak', sub: 'Singapore, India, US cùng peak tháng 6. Focus: Klook listings live sẵn từ tháng 5. DIFF đang chạy mỗi Thứ Bảy.' },
      headline: 'Singapore June holiday peak — tháng mạnh nhất cho Asian markets trong cả năm.',
      sub: 'Ấn Độ vẫn cao, SG đỉnh điểm, Mỹ-Canada bắt đầu — Central Coast vẫn DRY trong khi cả miền Bắc vào mưa; Klook là sàn ưu tiên số 1 tháng này.',
      featuredTours: ['ha-giang-jeep', 'bana-hills', 'india-halong', 'hoi-an-wellness', 'mekong-delta'],
      featuredMarkets: ['sg', 'in', 'us', 'ca'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Đỉnh mùa khô', note: 'DRY SEASON tiếp tục — tốt nhất năm cho beach + cultural' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Tốt', note: 'Mưa chiều ngắn 2–3h, không ảnh hưởng ban ngày' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Push mạnh', note: 'Ruộng bậc thang xanh mướt — rice terraces photogenic peak' },
        { region: 'Hà Nội', status: 'green', label: 'Tốt', note: 'Window cuối tốt trước Jul–Aug cực nóng' },
        { region: 'Phú Quốc', status: 'red', label: 'Tránh', note: 'Mùa mưa SW monsoon — gió Tây mạnh, experience kém; tắt promotion' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Tốt', note: 'Còn OK trước mùa typhoon tháng 7' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 30, gyg: 14, klook: 32, makemytrip: 16, direct: 8 },
      summary: { totalBookings: '~82,000', vsLastYear: '+20%', avgStay: '10 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'klook', reason: 'Klook 32% — SG, India, PH cùng active trên Klook tháng 6. Operator chưa có listing tiếng Anh chuẩn trên Klook là đang bỏ lại tiền trên bàn. Singapore book last-minute (2–3 tuần) — listing phải live và optimized trước 24/5 khi SG holiday bắt đầu.' },
      pullquote: 'Klook là sàn của tháng 6 — Singapore, Ấn, PH cùng active; operator nào chưa optimize listing tiếng Anh cho Klook Asian markets là đang nhìn tiền trôi qua cửa sổ.',
      insight: {
        opp: 'Singapore school holiday 24/5–29/6 (MOE Term 2 Break 2025) — SG family book last-minute 2–3 tuần, nhiều book từ cuối tháng 5; đừng để hết slot. DIFF đang diễn ra mỗi Thứ Bảy + Hoi An Full Moon 9/6/2025 (14 âm tháng 5) là combo tự nhiên — package "Lantern Night to DIFF" hấp dẫn nếu khách ở 2–3 tuần. India summer vẫn đang peak đến ~11/6 (CBSE).',
        risk: 'Singapore break bắt đầu từ 24/5, không phải 5/6 — listing cần live sẵn từ giữa tháng 5. Phú Quốc: tắt hoàn toàn paid promotion — gió Tây sẽ phá experience và review. Confirm guide + jeep driver Ha Giang cho tháng 6 ngay. Philippines summer kết thúc 15/6 — PH traffic drop sau đó.',
      },
    },
    {
      id: 7, name: 'Tháng 7', short: 'T7', hasData: true,
      phase: { mode: 'execute', label: 'Execute — peak hè đôi', sub: 'Khách đang travel. Focus: delivery, upsell on-trip, collect review. Listing optimization cho T7 đã phải xong từ T4.' },
      headline: 'Tháng collision — lịch nghỉ hè Tây và Á đổ vào Việt Nam cùng lúc, không tháng nào khác trong năm làm được điều này.',
      sub: 'Cơ hội lớn nhất năm nhưng miền Bắc mưa nặng và Hạ Long rủi ro bão — ai bán đúng điểm đến thắng lớn, ai bán sai mất review và mất khách.',
      featuredTours: ['ha-giang-jeep', 'hanoi-food-night', 'mekong-delta', 'hoi-an-wellness', 'sapa-trek'],
      featuredMarkets: ['us', 'au', 'ca', 'uk', 'ie'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Lợi thế cạnh tranh', note: 'Vẫn DRY khi toàn miền Bắc mưa — đây là secret cần bán' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Mekong đỉnh cao', note: 'Flood season bắt đầu — floating markets HIGH SEASON thật sự' },
        { region: 'Sapa / Hà Giang', status: 'yellow', label: 'Cẩn thận', note: 'Lúa xanh đỉnh đẹp nhưng landslide risk thật — brief khách kỹ' },
        { region: 'Hà Nội', status: 'yellow', label: 'Cẩn thận', note: '35–37°C ban ngày — chỉ push evening food tour, không push outdoor' },
        { region: 'Phú Quốc', status: 'red', label: 'Tránh', note: 'Cao điểm mùa mưa — gió Tây mạnh, sóng, tắt promotion hoàn toàn' },
        { region: 'Hạ Long Bay', status: 'red', label: 'Tránh', note: 'Typhoon risk lịch sử 5–15% cancel rate — tắt paid promotion' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 40, gyg: 25, klook: 18, makemytrip: 8, direct: 9 },
      summary: { totalBookings: '~148,000', vsLastYear: '+18%', avgStay: '12 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'viator', reason: 'Viator 40% chủ lực từ US/UK/AU. Klook 18% từ Asian market (SG, PH, India late). Listing cần có trên cả hai — Viator cho Western, Klook cho Asian. Direct chỉ 9% — khách hè không có thời gian research, cần OTA visibility. Không bỏ GYG — EU market (Scotland, Ireland) đang peak.' },
      pullquote: 'Tháng 7 không phải peak season — đây là collision season. Ai định vị đúng điểm đến thắng; ai đẩy Hạ Long và Phú Quốc không check thời tiết sẽ tự hại mình bằng review xấu.',
      insight: {
        opp: 'Central Coast DRY tháng 7 là competitive advantage lớn nhất trong năm — khi Hà Nội 37°C và Sapa mưa, Đà Nẵng đang ở mùa khô đẹp nhất. Đây là câu bán hàng chưa có đối thủ. DIFF Finals tối 12/7/2025 (Thứ Bảy) + Full Moon Hội An 9/7 (14 âm tháng 6 — năm 2025 có Tháng 6 Nhuận) cùng trong một tháng — package "Lantern Night to DIFF Finals" hấp dẫn nếu khách ở 2–3 tuần.',
        risk: 'Tắt ngay paid promotion Halong cruise và toàn bộ Phú Quốc beach. Confirm hợp đồng guide + jeep Ha Giang cả tháng 7 — nếu chưa, guide tốt đã bị đối thủ giữ slot. Canada Day 1/7 là Thứ Ba năm 2025, không tạo long weekend tự động — không cần push "4-day getaway". AU winter break ~28/6–13/7 (NSW/VIC) là window hẹp, cần listing live từ tháng 5.',
      },
    },
    {
      id: 8, name: 'Tháng 8', short: 'T8', hasData: true,
      phase: { mode: 'execute', label: 'Execute — UK/US late summer', sub: 'England peak hè, US late summer. Focus: Mekong + Miền Trung delivery. SG Term 3 break bắt đầu 30/8 — Klook listing phải live sẵn.' },
      headline: 'Anh England vào peak, Mỹ late summer — Mekong lên nước cao nhất, competitive advantage thật sự cho ai biết cách kể.',
      sub: 'Miền Bắc núi nguy hiểm nhất năm — dừng push Sapa/Hà Giang, chuyển toàn bộ budget sang Mekong và Miền Trung trước khi hết window khô.',
      featuredTours: ['mekong-delta', 'hoi-an-wellness', 'hanoi-food-night', 'saigon-vespa'],
      featuredMarkets: ['uk', 'us', 'ie', 'sg'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'green', label: 'Cuối mùa khô', note: 'Còn dry nhưng độ ẩm tăng cuối tháng — push mạnh đầu tháng 8' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Mekong đỉnh', note: 'Flood season cao điểm — floating markets đẹp và nhộn nhịp nhất' },
        { region: 'Sapa / Hà Giang', status: 'red', label: 'Tránh', note: 'Mưa nặng nhất năm + landslide risk cao — dừng sell hoàn toàn' },
        { region: 'Hà Nội', status: 'yellow', label: 'Cẩn thận', note: '28–29°C nóng ẩm, mưa hàng ngày — evening tour only' },
        { region: 'Phú Quốc', status: 'red', label: 'Tránh', note: 'Peak mùa mưa — gió + sóng + experience kém' },
        { region: 'Hạ Long Bay', status: 'red', label: 'Tránh', note: 'Typhoon risk tiếp tục — giảm hiển thị, không xóa listing' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 42, gyg: 22, klook: 17, makemytrip: 10, direct: 9 },
      summary: { totalBookings: '~128,000', vsLastYear: '+15%', avgStay: '11 ngày', topRegion: 'Miền Trung + Nam' },
      otaRec: { ota: 'viator', reason: 'Viator 42% cao nhất năm — UK England + US late summer = Western peak. GYG 22% từ European market. Klook 17% bắt đầu tăng lại từ SG National Day 9/8 (Sat) và SG Term 3 break bắt đầu 30/8 — chuẩn bị Klook listing trước.' },
      pullquote: 'Tháng 8 Mekong lên nước — đây không phải mùa lũ đáng sợ, đây là high season thật sự của delta; chỉ cần operator biết cách kể lại câu chuyện đó.',
      insight: {
        opp: 'Mekong Delta tháng 8 là high season thật sự — nước dâng cao nhất, floating markets nhộn nhịp nhất, cảnh đẹp nhất. Reframe messaging: "Mekong Rising Waters — peak season for floating markets." Singapore National Day 9/8 (Thứ Bảy 2025) tạo 3-day weekend — Klook last-minute listings cho HCMC day tours có thể capture. Full Moon Hội An 7/8/2025 (14 âm tháng 6 Nhuận) là sự kiện được tìm kiếm nhiều — cập nhật listing date đúng. SG Term 3 break bắt đầu 30/8 — listing phải live sẵn từ giữa tháng 8.',
        risk: 'Sapa/Hà Giang còn booking đã xác nhận → brief khách về landslide risk và có plan B ngay. Miền Trung đang ở cuối dry season — không over-promise "beach perfect" cho late August khi độ ẩm và mây bắt đầu tăng. Cập nhật listing Hội An Full Moon: sự kiện là 7/8, không phải 23/8 (2025 có Tháng 6 Nhuận).',
      },
    },
    {
      id: 9, name: 'Tháng 9', short: 'T9', hasData: true,
      phase: { mode: 'book', label: 'Execute SG break + Book T10–T11', sub: 'SG Term 3 break 30/8–14/9 đang travel. AU/NZ Term 3 break late Sep. Đây là window book Ha Giang cho T10 — sold out sớm.' },
      headline: 'Mùa vàng Sapa bắt đầu — Northern mountains đột ngột trở thành điểm đến hấp dẫn nhất sau 2 tháng mưa.',
      sub: 'SG Term 3 break bắt đầu 30/8 (không phải 5/9) và Úc/NZ Term 3 break late Sep — volume khiêm tốn nhưng Mu Cang Chai paragliding mid-Sep là packaging cơ hội hiếm có. Mid-Autumn Festival 2025 rơi vào 6/10 (T10), không phải tháng 9.',
      featuredTours: ['ha-giang-jeep', 'sapa-trek', 'hanoi-food-night', 'mekong-delta'],
      featuredMarkets: ['sg', 'au', 'nz'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'yellow', label: 'Cẩn thận', note: 'Mùa mưa bắt đầu Sep–Nov — risk bão tăng dần; dừng push beach' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Tốt', note: 'Mekong vẫn peak flood; HCMC urban không bị ảnh hưởng' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Đỉnh vàng', note: 'Harvest season bắt đầu — lúa chín vàng, tháng đẹp nhất năm' },
        { region: 'Hà Nội', status: 'green', label: 'Tốt', note: 'Mát hơn, ít mưa hơn, dễ chịu — best Sep month' },
        { region: 'Phú Quốc', status: 'yellow', label: 'Cẩn thận', note: 'Cuối mùa mưa, giá rẻ 20–30%, east beach vẫn calm' },
        { region: 'Hạ Long Bay', status: 'yellow', label: 'Cẩn thận', note: 'Cải thiện dần nhưng vẫn còn risk bão sót' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 28, gyg: 17, klook: 35, makemytrip: 8, direct: 12 },
      summary: { totalBookings: '~52,000', vsLastYear: '+13%', avgStay: '10 ngày', topRegion: 'Miền Bắc' },
      otaRec: { ota: 'klook', reason: 'Klook 35% cao nhất T9 — SG Term 3 break (30/8–14/9) và AU/NZ late Sep là Asian market tháng này. SG book last-minute, Klook là sàn chính. Update hero image listing Sapa/Ha Giang sang lúa vàng trước 30/8 — conversion sẽ tăng ngay.' },
      pullquote: 'Tháng 9 là tháng Sapa sold out mà nhiều operator không biết mình có gì để bán; hero image lúa vàng trên listing là đủ để double conversion — nhưng phải có trước 30/8 vì SG break đã bắt đầu rồi.',
      insight: {
        opp: 'Harvest season Sapa/Hà Giang tháng 9 là content gold — lúa vàng chụp ảnh đẹp nhất, nhưng nhiều operator chưa update hero image listing từ ảnh lúa xanh tháng 6. Update ngay trước 1/9 để capture SG Sep break (bắt đầu 30/8). Mu Cang Chai paragliding mid-Sep (~20–22/9) kết hợp AU/NZ Sep break là combo hiếm — "Paragliding + Harvest Trek" tạo urgency tự nhiên. Lưu ý: Mid-Autumn Festival 2025 là 6/10 (T10), không phải tháng 9.',
        risk: 'Central Coast bắt đầu mưa — dừng push Da Nang/Hoi An beach tours tháng 9, redirect traffic sang Sapa/Ha Giang harvest content. Singapore break bắt đầu từ 30/8, không phải 5/9 — listing cần live sẵn từ giữa tháng 8. Phong Nha caves bắt đầu có risk flooding — check forecast trước khi confirm.',
      },
    },
    {
      id: 10, name: 'Tháng 10', short: 'T10', hasData: true,
      phase: { mode: 'book', label: 'Book T12 + Execute harvest peak', sub: 'Ha Giang lúa vàng đỉnh + cruise season mở lại. Song song: T12 holiday window đang mở — khách Mỹ, Anh book Dec từ tháng 8–9. Audit listing ngay.' },
      headline: 'Harvest peak Hà Giang + Cruise season mở lại — Central Coast bão hoàn toàn, Mid-Autumn Festival 6/10 là event highlight.',
      sub: 'AU/NZ/UK half-term late Oct tạo volume vừa phải; lúa vàng Sapa và Mu Cang Chai là attraction lớn nhất năm cho photography traveler — book từ tháng 8 mới có slot.',
      featuredTours: ['ha-giang-jeep', 'sapa-trek', 'india-halong', 'hanoi-food-night'],
      featuredMarkets: ['au', 'nz', 'in', 'uk'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'red', label: 'Tránh', note: 'Peak bão Oct–Nov — risk cao nhất năm; tắt paid promotion' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Tốt', note: 'Chuyển sang dry season — ổn định, comfortable' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Đỉnh photography', note: 'Lúa chín vàng rực nhất — tháng đẹp nhất năm' },
        { region: 'Hà Nội / Ninh Bình', status: 'green', label: 'Push mạnh', note: 'Mát mẻ 20–24°C, ít mưa — best autumn month' },
        { region: 'Phú Quốc', status: 'green', label: 'Đang cải thiện', note: 'Cuối mùa mưa, early recovery — giá hấp dẫn' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Cruise peak mở lại', note: 'Oct là điểm đầu cruise season mới — biển êm trở lại, push mạnh' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 35, gyg: 22, klook: 22, makemytrip: 10, direct: 11 },
      summary: { totalBookings: '~92,000', vsLastYear: '+22%', avgStay: '13 ngày', topRegion: 'Miền Bắc' },
      otaRec: { ota: 'gyg', reason: 'GYG và Viator ngang nhau T10 — Viator 35% (AU/NZ/US), GYG 22% tăng từ European market quay lại. Klook 22% từ India Diwali window và SG. Thêm tag "Golden Rice Terraces", "Ha Giang October" vào listing. Direct 11% = khách repeat từ mùa hè — push email.' },
      pullquote: 'Tháng 10 có một điều chắc chắn: Hà Giang lúa vàng sold out. Operator nào chưa book guide từ tháng 8 là đã hết slot tốt.',
      insight: {
        opp: 'Ha Giang và Sapa tháng 10 là top-performing months — guide và jeep driver khan hiếm nhất năm; operator book supplier từ tháng 8 thắng. Halong cruise recovery tháng 10 là cơ hội re-activate India Cruise tier trước Dec peak. Diwali 20/10/2025 tạo post-festival travel window cho India market — package "Post-Diwali Escape to Vietnam" có conversion tốt. Mid-Autumn 6/10/2025 (15 tháng 8 âm lịch) là event hấp dẫn cho family travelers — Hoi An Lantern Night đầu tháng là điểm nhấn duy nhất trước bão.',
        risk: 'Central Coast hoàn toàn đỏ tháng 10 — tắt paid promotion Đà Nẵng/Hội An hoặc kèm flexible cancellation rất rõ ràng. Phong Nha caves: AVOID — flooding cao điểm. Hội An Mid-Autumn 6/10 có risk bão tail — cần flexible policy rõ ràng trong listing.',
      },
    },
    {
      id: 11, name: 'Tháng 11', short: 'T11', hasData: true,
      phase: { mode: 'execute', label: 'Execute — US Thanksgiving + cruise peak', sub: 'Thanksgiving 27/11 là booking surge US. Khách Âu đang travel dài ngày. Focus: premium experience + Viator listing rõ ràng cho Dec–Jan.' },
      headline: 'Mùa đỉnh đang đến — Thanksgiving Mỹ bật spike và cruise season vào guồng toàn lực.',
      sub: 'Thời tiết toàn quốc bắt đầu ổn định, khách Tây Phương book sớm cho Xmas — tháng của advance booking và listing refresh, không phải walk-in.',
      featuredTours: ['india-halong', 'hanoi-food-night', 'hoi-an-wellness', 'sapa-trek'],
      featuredMarkets: ['us', 'in', 'sg', 'uk'],
      destinations: [
        { region: 'Đà Nẵng / Hội An / Nha Trang', status: 'yellow', label: 'Cẩn thận', note: 'Mưa đầu tháng (bão tail Oct–Nov), khô dần cuối Nov — push tour cuối tháng an toàn hơn' },
        { region: 'HCMC / Đà Lạt / Mekong', status: 'green', label: 'Push mạnh', note: 'Cool dry bắt đầu — comfortable, Mekong đẹp cuối mùa lũ' },
        { region: 'Sapa / Hà Giang', status: 'green', label: 'Tốt', note: 'Cool, dry, clear — sương nhẹ sáng sớm, đẹp' },
        { region: 'Hà Nội', status: 'green', label: 'Push mạnh', note: 'Cool dry 18–22°C — một trong những tháng đẹp nhất Hà Nội' },
        { region: 'Phú Quốc', status: 'green', label: 'Push mạnh', note: 'Mùa khô bắt đầu — nắng trở lại, beach OK' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Push mạnh', note: 'Cruise season đang vào đỉnh — biển êm, mát mẻ' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 40, gyg: 19, klook: 16, makemytrip: 16, direct: 9 },
      summary: { totalBookings: '~78,000', vsLastYear: '+19%', avgStay: '14 ngày', topRegion: 'Miền Trung' },
      otaRec: { ota: 'viator', reason: 'Viator 40% T11 — US Thanksgiving (27/11) surge + UK Xmas booking. MakeMyTrip tăng trở lại 16% (India winter peak bắt đầu). Operator có Viator listing rõ ràng cho Dec–Jan trước 27/11 sẽ capture booking surge tốt nhất.' },
      pullquote: 'Thanksgiving Mỹ không phải ngày du lịch — đó là ngày Mỹ quyết định ai đặt được Xmas VN và ai không; Viator listing của bạn ngày 27/11 đó có sẵn sàng không?',
      insight: {
        opp: 'Thanksgiving US 27/11/2025 (4th Thursday) không chỉ là travel trigger — đây là thời điểm US families confirm Xmas booking. Operator có listing rõ ràng cho Dec–Jan trên Viator trước 27/11 sẽ capture booking surge tốt nhất. MakeMyTrip 16% — re-activate "Winter Cruise Season November to March" với listing title rõ ràng. Post-Diwali India travelers từ T10 tiếp tục đặt tour T11–T12.',
        risk: 'Central Coast cẩn thận đầu tháng 11 — đừng sell Da Nang beach tour cho đầu tháng; push cuối tháng khi bão đã qua. Hội An tháng 11 vẫn có risk bão tail — flexible cancellation policy bắt buộc cho tour outdoor Miền Trung. Lock vendor contract Xmas trước khi giá tăng.',
      },
    },
    {
      id: 12, name: 'Tháng 12', short: 'T12', hasData: true,
      phase: { mode: 'execute', label: 'Execute — holiday peak', sub: 'Khách Christmas/NY đang travel. Giá cao nhất năm. Focus: zero cancellation, review push, upsell add-on. Đồng thời: book T3 (spring break) mở từ giữa tháng.' },
      headline: 'Đỉnh tuyệt đối — Xmas/NY kéo mọi thị trường về VN cùng lúc, 3 tuần Dec 15–Jan 5 chiếm phần lớn doanh thu quý 4.',
      sub: 'Cruise season peak, Philippines Xmas, Úc summer — nếu đến tháng 12 bạn vẫn còn slot trống tuần 20–31/12, vấn đề là pricing, không phải demand.',
      featuredTours: ['india-halong', 'hoi-an-wellness', 'phu-quoc-snorkel', 'saigon-vespa', 'hanoi-food-night'],
      featuredMarkets: ['us', 'ph', 'au', 'uk'],
      destinations: [
        { region: 'Phú Quốc / Nha Trang / Côn Đảo', status: 'green', label: 'Đỉnh mùa khô', note: 'Peak beach — nắng đẹp nhất, biển lặng; upsell premium resort' },
        { region: 'Hội An / Đà Nẵng', status: 'green', label: 'Đỉnh điểm', note: 'Cool dry 21–24°C — best month Miền Trung; Christmas atmosphere' },
        { region: 'HCMC', status: 'green', label: 'Đỉnh điểm', note: 'Warm dry excellent, Xmas atmosphere sôi động' },
        { region: 'Hà Nội', status: 'green', label: 'Push mạnh', note: 'Cool 16–21°C, đèn Xmas đẹp, atmosphere tốt' },
        { region: 'Sapa / Hà Giang', status: 'yellow', label: 'Cẩn thận', note: 'Sương mù + rét đậm có thể xảy ra — brief khách về fog risk' },
        { region: 'Hạ Long Bay', status: 'green', label: 'Đỉnh cruise', note: 'Peak season — cruise sold out từ T10 nếu book đúng lịch' },
      ],
      otaShare: ['viator', 'gyg', 'klook', 'makemytrip', 'direct'],
      otaShareData: { viator: 38, gyg: 17, klook: 20, makemytrip: 10, direct: 15 },
      summary: { totalBookings: '~118,000', vsLastYear: '+21%', avgStay: '11 ngày', topRegion: 'Miền Nam + Trung' },
      otaRec: { ota: 'direct', reason: 'Direct 15% — cao nhất năm (chỉ sau T11). Khách holiday premium hay book thẳng để chắc chắn. Klook 20% từ Philippines Xmas peak (Simbang Gabi 16/12) và AU summer. T12 là tháng đầu tư direct channel nhất: email blast "Christmas in Vietnam", package premium với add-on NYE countdown.' },
      pullquote: 'Tháng 12 không cần bán — cần quản lý capacity; nếu bạn còn slot trống tuần Dec 20–31, đó là vấn đề giá, không phải vấn đề demand.',
      insight: {
        opp: 'Tháng 12 là tháng quản lý capacity, không phải tháng bán thêm. Halong cruise sold out từ tháng 10 nếu operator đã book đúng lúc. Philippines barkada Dec là peak duy nhất trong năm mà HCMC có thể charge premium — Simbang Gabi 16/12–24/12 là peak window thực sự, upsell VIP tier. Direct channel 15% — cao nhất năm, khách quen quay lại hoặc referral từ khách cũ. Nurture repeat relationship.',
        risk: 'Sapa/Hà Giang fog risk tháng 12 — brief rõ trong booking confirmation, không để surprise on-spot. Lock vendor contract trước tháng 11 (giá Xmas tăng 20–40%). Tết VN 2026 rơi vào 17/2/2026 — brief khách Dec travel về Tết schedule ngay khi confirm để tránh conflict khi họ extend trip sang Feb. AU summer holidays: WA ~19/12, QLD ~20/12, NSW ~22/12 — AU families thích beach + resort (Phú Quốc, Nha Trang).',
      },
    },
  ],

  tours: [
    { name: 'Hà Giang Jeep 4N3Đ',
      region: 'Bắc', province: 'Hà Giang',
      price: '$180–$280', priceLow: 180, priceHigh: 280,
      desc: 'Ma Pi Leng + Đồng Văn karst plateau. Enclosed cabin, phù hợp khách 35+ không thích xe máy.',
      peakMonths: [9, 10, 11], shoulderMonths: [7],
      hotInMonth: { 7: 'Lúa xanh đỉnh, enclosed cabin tránh mưa' },
      markets: ['au', 'us'],
      otas: ['viator', 'gyg'],
      bookings: { 7: 1240, 1: 520, 2: 480, 3: 650, 9: 1800, 10: 2100 },
      hotInMonth: { 7: 'Lúa xanh đỉnh, enclosed cabin tránh mưa', 1: 'Enclosed cabin tránh rét, Bắc VN cool dry — tốt cho 35+', 2: 'Dry season, trước mưa xuân', 3: 'Trước mùa mưa — đường đẹp nhất Q1', 9: 'Lúa chín vàng — ảnh đẹp nhất năm', 10: 'Lúa vàng còn đó, thời tiết mát — push Âu khách' },
      rating: 4.7, reviews: 395,
      hasDetail: true,
      competitors: [
        { name: 'Open Air Jeep HG', ota: 'gyg', reviews: 395, rating: 4.7, price: '$165', diff: 'Open-air Land Rover cổ' },
        { name: 'HG Loop Easy Rider', ota: 'viator', reviews: 1200, rating: 4.8, price: '$220', diff: 'Motorbike + driver' },
        { name: 'Vietnam Motorcycle Tours', ota: 'viator', reviews: 800, rating: 4.6, price: '$280', diff: 'Tự lái' },
      ],
      usp: 'Enclosed cabin tránh mưa + phù hợp 35+ không thích xe máy.',
    },
    {
      id: 'hoi-an-wellness', name: 'Hội An Wellness Day',
      region: 'Trung', province: 'Hội An',
      price: '$85–$120', priceLow: 85, priceHigh: 120,
      desc: 'Spa + cooking class + cycling. Lantern Festival 25/7.',
      peakMonths: [3, 4, 7, 8], shoulderMonths: [],
      hotInMonth: { 7: 'Mùa khô + Lantern Festival 25/7' },
      markets: ['us', 'au'],
      otas: ['viator'],
      bookings: { 7: 890, 1: 4400, 2: 2100, 3: 5100, 10: 1800, 11: 2200 },
      hotInMonth: { 7: 'Mùa khô + Lantern Festival 25/7', 1: '22–25°C outdoor, Ancient Town đẹp mùa khô', 2: 'Peak dry season Miền Trung — thời tiết tốt nhất năm', 3: 'Dry tail 24–27°C — Miền Trung vẫn lý tưởng', 10: 'Khô đẹp, tiền bão lùi xa', 11: 'Khô nhất năm — kết hợp Huế Hội An' },
      rating: 4.8, reviews: 612,
    },
    {
      id: 'india-halong', name: 'India Halong Cruise',
      region: 'Bắc', province: 'Hạ Long',
      price: '$220–$380', priceLow: 220, priceHigh: 380,
      desc: 'Family-friendly cruise, Jain meal option, Hindi-speaking guide.',
      peakMonths: [5, 6, 7, 8], shoulderMonths: [],
      hotInMonth: { 7: 'Direct flights, mùa hè Ấn nóng' },
      markets: ['in'],
      otas: ['makemytrip'],
      bookings: { 7: 540, 1: 8500, 2: 7800, 3: 9200, 5: 620, 6: 710, 8: 580, 12: 450 },
      hotInMonth: { 7: 'Direct flights, mùa hè Ấn nóng', 1: 'Biển êm, cool dry — tháng tốt nhất cho cruise', 2: 'Cruise window mạnh, biển êm', 3: 'Cruise season peak — March cao nhất Q1', 12: 'Holiday cruise — premium tier fill rate cao' },
      rating: 4.5, reviews: 178,
    },
    {
      id: 'ph-barkada', name: 'PH Barkada HCMC 4D3N',
      region: 'Nam', province: 'HCMC',
      price: '$380–$520', priceLow: 380, priceHigh: 520,
      desc: 'Group package 6 người, urban + food + shopping.',
      peakMonths: [4, 5, 6, 7], shoulderMonths: [],
      hotInMonth: { 7: 'Summer break PH, urban ít mưa' },
      markets: ['ph'],
      otas: ['klook'],
      bookings: { 7: 720, 3: 680, 4: 890, 5: 950, 6: 840 },
      hotInMonth: { 7: 'Summer break PH, urban ít mưa', 3: 'Inter-term PH, nhóm bạn đi ngắn', 4: 'Summer break PH bắt đầu', 5: 'Peak PH summer' },
      rating: 4.6, reviews: 234,
    },
    {
      id: 'hanoi-food-night', name: 'Hà Nội Street Food Night',
      region: 'Bắc', province: 'Hà Nội',
      price: '$35–$55', priceLow: 35, priceHigh: 55,
      desc: 'Walking food tour Old Quarter, 3 giờ, 8 món, bia hơi.',
      peakMonths: [10, 11, 12, 3, 4], shoulderMonths: [7],
      hotInMonth: { 7: '37°C ban ngày, đêm mát + sôi động' },
      markets: ['uk', 'us'],
      otas: ['viator', 'klook'],
      bookings: { 7: 2150, 1: 6200, 2: 5200, 3: 7400, 10: 3800, 11: 4200, 12: 3100 },
      hotInMonth: { 7: '37°C ban ngày, đêm mát + sôi động', 1: '15–18°C ban đêm — lý tưởng cho evening walk food tour', 2: '15–20°C — tháng đẹp nhất cho Hanoi walking', 3: 'Volume ổn định, spring break US gia đình', 10: 'Thu Hà Nội 20–26°C, không mưa', 11: 'Thu vàng Hà Nội — khách Âu rất thích', 12: 'Holiday season, night market sôi động' },
      rating: 4.8, reviews: 4794,
    },
    {
      id: 'bana-hills', name: 'Ba Na Hills Golden Bridge',
      region: 'Trung', province: 'Đà Nẵng',
      price: '$65–$95', priceLow: 65, priceHigh: 95,
      desc: 'Day trip cáp treo + Golden Bridge + French Village.',
      peakMonths: [4, 5, 6, 7, 8], shoulderMonths: [],
      hotInMonth: { 7: 'Đà Nẵng dry + Bà Nà 1,400m mát' },
      markets: ['in', 'us'],
      otas: ['klook', 'viator'],
      bookings: { 7: 1680, 1: 3100, 2: 2800, 3: 2600, 10: 2200, 11: 1900 },
      hotInMonth: { 7: 'Đà Nẵng dry + Bà Nà 1,400m mát', 1: 'Da Nang mùa khô, cáp treo không bị mây mù', 2: 'Peak dry Đà Nẵng — tầm nhìn đẹp nhất', 3: 'Dry tail — vẫn rất tốt', 10: 'Khô + mát — thời tiết tốt nhất Bà Nà' },
      rating: 4.5, reviews: 1230,
    },
    // Placeholder tours
    { id: 'sapa-trek', name: 'Sapa Trek 2N1Đ', region: 'Bắc', province: 'Lào Cai', price: '$120–$180', markets: ['fr', 'de'], otas: ['viator', 'gyg'], rating: 4.6, reviews: 820, placeholder: true },
    { id: 'mekong-delta', name: 'Mekong Delta Day Trip', region: 'Nam', province: 'Tiền Giang', price: '$40–$70', markets: ['us', 'uk'], otas: ['klook'], rating: 4.3, reviews: 1540, placeholder: true },
    { id: 'phu-quoc-snorkel', name: 'Phú Quốc Snorkel', region: 'Nam', province: 'Kiên Giang', price: '$50–$80', markets: ['kr', 'ph'], otas: ['klook'], rating: 4.4, reviews: 920, placeholder: true },
    { id: 'hue-imperial', name: 'Huế Imperial City', region: 'Trung', province: 'Huế', price: '$60–$90', markets: ['fr', 'jp'], otas: ['viator'], rating: 4.5, reviews: 640, placeholder: true },
    { id: 'dalat-canyon', name: 'Đà Lạt Canyoning', region: 'Nam', province: 'Lâm Đồng', price: '$75–$110', markets: ['au', 'uk'], otas: ['gyg'], rating: 4.8, reviews: 1100, placeholder: true },
    { id: 'ninh-binh', name: 'Ninh Bình Tam Cốc', region: 'Bắc', province: 'Ninh Bình', price: '$55–$85', markets: ['us', 'fr'], otas: ['viator'], rating: 4.7, reviews: 2100, placeholder: true },
    { id: 'con-dao', name: 'Côn Đảo Historical', region: 'Nam', province: 'BR-VT', price: '$200–$350', markets: ['vn-diaspora'], otas: ['direct'], rating: 4.6, reviews: 180, placeholder: true },
    { id: 'nha-trang-spa', name: 'Nha Trang Spa & Beach', region: 'Trung', province: 'Khánh Hòa', price: '$90–$150', markets: ['ru', 'kr'], otas: ['klook'], rating: 4.4, reviews: 780, placeholder: true },
    { id: 'quy-nhon', name: 'Quy Nhơn Hidden Coast', region: 'Trung', province: 'Bình Định', price: '$110–$180', markets: ['au'], otas: ['direct'], rating: 4.7, reviews: 140, placeholder: true },
    { id: 'cat-ba', name: 'Cát Bà Kayak', region: 'Bắc', province: 'Hải Phòng', price: '$80–$130', markets: ['de', 'uk'], otas: ['gyg'], rating: 4.5, reviews: 560, placeholder: true },
    { id: 'saigon-vespa', name: 'Saigon Vespa Night', region: 'Nam', province: 'HCMC', price: '$70–$100', markets: ['au', 'us'], otas: ['viator'], rating: 4.9, reviews: 3400, placeholder: true },
    { id: 'pu-luong', name: 'Pù Luông Retreat', region: 'Bắc', province: 'Thanh Hóa', price: '$140–$220', markets: ['fr', 'de'], otas: ['direct'], rating: 4.8, reviews: 320, placeholder: true },
  ],

  markets: [
    {
      id: 'us', flag: '🇺🇸', name: 'Mỹ',
      demand7: 'CAO',
      volume: '~620,000 lượt/năm',
      hasDetail: true,
      peakMonths: [6, 7, 8, 12, 1],
      shoulderMonths: [3, 4, 9, 10],
      why7: 'Trường nghỉ hè, family book sớm',
      portrait: 'Couple 40–55 có con tuổi 8–16. Trường nghỉ hè, muốn 2–3 tuần ấm + cultural substance. Caribbean nhàm rồi, muốn "dinner-party story" kể được 3 tháng sau khi về.',
      budget: '$3,200–$7,000', leadTime: '6–8 tuần',
      party: '4–5 người', visa: 'e-visa 90 ngày',
      favTours: ['hanoi-food-night', 'india-halong', 'hoi-an-wellness', 'phu-quoc-snorkel'],
      favOtas: ['viator', 'direct'],
    },
    {
      id: 'au', flag: '🇦🇺', name: 'Úc',
      demand7: 'CAO',
      volume: '~390,000 lượt/năm',
      hasDetail: true,
      peakMonths: [6, 7, 12, 1],
      shoulderMonths: [4, 5, 9],
      why7: 'Winter break 27/6–12/7',
      portrait: 'Couple 35–55, nhiều retiree. Trốn mùa đông, thích adventure nhẹ + food. Đã đi Bali, Thái — VN là "next frontier". Ngại tour đông, thích boutique + small group.',
      budget: '$2,500–$5,500', leadTime: '8–12 tuần',
      party: '2–4 người', visa: 'e-visa 90 ngày',
      favTours: ['ha-giang-jeep', 'india-halong', 'sapa-trek'],
      favOtas: ['gyg', 'viator'],
    },
    {
      id: 'in', flag: '🇮🇳', name: 'Ấn Độ',
      demand7: 'TRUNG BÌNH',
      volume: '~746,000 lượt/năm (+49% YoY)',
      hasDetail: true,
      why7: 'Direct flights tăng, summer Ấn nóng 40°+',
      portrait: 'Gia đình mở rộng 6–10 người, 3 thế hệ. Book tour Hạ Long cruise có phòng family, bữa ăn Jain/vegetarian, hướng dẫn nói tiếng Hindi. Shop mạnh, chụp ảnh nhiều, không ưa adventure mạo hiểm.',
      budget: '$1,800–$3,500', leadTime: '4–6 tuần',
      party: '6–10 người', visa: 'e-visa 30/90 ngày',
      favTours: ['india-halong', 'bana-hills', 'phu-quoc-snorkel'],
      favOtas: ['makemytrip', 'klook'],
      peakMonths: [5, 6, 7, 8, 12],
      shoulderMonths: [4, 10, 11],
      personas: [
        {
          id: 'value-max',
          tier: 'PRIMARY',
          name: 'Value-Max Family Group',
          age: '30–50',
          size: 'Gia đình + nhóm bạn 6–10 người (3 thế hệ)',
          share: 75,
          budget: '$200/người/ngày · Tổng booking $1,200–1,600',
          motivation: 'Value for money · Package all-in · Veg/Jain food · Safety · Family-friendly',
          trigger: '"Pure Veg Certified" badge · Group discount · Transfer included',
          pain: 'Không có hướng dẫn Hindi · Bếp không tách biệt · Giá không có group rate',
          booking: 'MakeMyTrip + WhatsApp agent · 30–60 ngày trước · 75–85% mobile',
          device: 'Mobile-first · UPI / NetBanking',
        },
        {
          id: 'affluent-multigen',
          tier: 'SECONDARY',
          name: 'Affluent Multi-Gen HNI',
          age: '35–65 (3 thế hệ)',
          size: 'Gia đình 4–8 người HNI Mumbai / Delhi',
          share: 20,
          budget: '$300–500/người/ngày',
          motivation: 'Luxury junk · Onboard yoga · Pure-veg fine dining · Multi-gen accessible',
          trigger: 'Jain certification · Butler service · Stateroom upgrade',
          pain: 'Thiếu accessibility (grab bars, elevator) · Guide không nói Hindi · Menu không đủ regional variation',
          booking: 'Thomas Cook India · SOTC · Boutique concierge · 8–12 tuần trước',
          device: 'Web + mobile · Credit card / bank wire',
        },
        {
          id: 'nri',
          tier: 'TERTIARY',
          name: 'NRI Returnee (UK/US/CA/AU)',
          age: '28–45',
          size: 'Couple hoặc gia đình nhỏ 2–4 người',
          share: 5,
          budget: '$200–350/người/ngày',
          motivation: 'Kết hợp Jain food + Western comfort + English guide',
          trigger: 'Viator / GYG reviews · English listing quality',
          pain: 'Không đủ English-language support trong OTA Ấn · Mất tin tưởng brand mới',
          booking: 'Viator / GetYourGuide · 6–10 tuần trước',
          device: 'Desktop + mobile · Credit card',
        },
      ],
      booking: {
        channels: [
          { name: 'MakeMyTrip', role: 'PRIMARY', note: 'Bundle flight+hotel+tour · 70%+ India inbound qua đây · Commission 15–22%' },
          { name: 'WhatsApp Agent', role: 'PRIMARY', note: 'Groups 200–500 khách · Promo push peak seasons · Parallel với OTA' },
          { name: 'Yatra / Goibibo', role: 'SECONDARY', note: 'Mobile-heavy tier-2 cities · Cùng group MMT' },
          { name: 'Klook', role: 'SECONDARY', note: 'NRI Singapore / Malaysia segment' },
          { name: 'Viator / GYG', role: 'TERTIARY', note: 'NRI UK/US/CA/AU chủ yếu' },
        ],
        leadTime: '30–60 ngày (group) · 7–14 ngày (solo professional)',
        device: '75–85% mobile',
        payment: 'UPI · NetBanking · EMI',
        trigger: '"Pure Veg Certified" badge · Group discount expected · Package all-in (transfer + cruise + meals)',
      },
      localization: [
        { lever: 'Thực phẩm', what: 'Pure Veg + Jain-certified kitchen (no root veg) · Masala chai riêng · Menu Gujarati / South Indian option' },
        { lever: 'Ngôn ngữ', what: 'Hindi-speaking guide bắt buộc · Listing mô tả Hindi + English · Materials song ngữ' },
        { lever: 'Thanh toán', what: 'UPI · NetBanking · EMI installment · Giá niêm yết INR' },
        { lever: 'Nhóm & gia đình', what: 'Group discount 6+ pax expected · Family suite cabins · Multi-gen accessibility (grab bars)' },
        { lever: 'Trust signal', what: '"Jain Certified" badge · WhatsApp response ≤2h · Indian community endorsement' },
        { lever: 'Lịch lễ', what: 'Diwali ~Nov 1 (+25% premium) · India summer May–Jun · Independence Day Aug 15' },
      ],
      opportunity: 'Gap 99K–228K khách/năm chưa được phục vụ đúng nghĩa — Jain-certified kitchen + Hindi guide pipeline là operational moat khó copy trong 90 ngày. T10 (India Halong Cruise) fill tháng Oct–Feb khi Western tours thiếu demand.',
      risk: '1 incident cross-contamination kitchen = brand destruction trong cộng đồng Jain qua WhatsApp trong 1 tháng. Typhoon Jul–Sep Halong. Guide pipeline mỏng — roster 6 guide cho 4-guide need.',
    },
    {
      id: 'ph', flag: '🇵🇭', name: 'Philippines',
      demand7: 'TRUNG BÌNH',
      volume: '~240,000 lượt/năm (+95% YoY 2023→2024)',
      hasDetail: true,
      why7: 'Summer break tail — trường học kết thúc đầu tháng',
      portrait: 'Nhóm bạn "barkada" 5–8 người, tuổi 25–35. Đi 3–4 ngày, thích urban + food + shopping + cafe check-in. Không quan tâm "văn hoá sâu", quan tâm content Instagram. Ngân sách thấp nhưng chi mạnh cho F&B + vui chơi.',
      budget: '$400–$700', leadTime: '3–5 tuần',
      party: '5–8 người', visa: 'miễn 21 ngày',
      favTours: ['ph-barkada', 'phu-quoc-snorkel', 'saigon-vespa'],
      favOtas: ['klook', 'viator'],
      peakMonths: [4, 5, 6, 7],
      shoulderMonths: [3, 10, 11, 12],
      personas: [
        {
          id: 'barkada',
          tier: 'PRIMARY',
          name: 'Barkada Gen-Z Group',
          age: '22–32',
          size: 'Nhóm bạn 5–8 người',
          share: 50,
          budget: '₱35,000–55,000/người ($600–950)',
          motivation: 'Instagram content · Food + cafe · Urban shopping · Giá rẻ hơn Bali',
          trigger: 'Flash sale Klook · TikTok review · Klook Points reward',
          pain: 'Tour không có Messenger support · Giá không peso · Không có group package',
          booking: 'Klook PH · Instagram DM · Facebook Messenger · 3–5 tuần trước',
          device: '90%+ mobile · GCash / PayMaya',
        },
        {
          id: 'family-multigen',
          tier: 'SECONDARY',
          name: 'Family Multigen (Catholic)',
          age: '35–60 (3 thế hệ)',
          size: 'Gia đình 4–8 người (abuela/abuelo đi cùng)',
          share: 20,
          budget: '₱80,000–150,000 tổng group',
          motivation: 'School holiday · Xmas / All Saints family trip · Biển + resort',
          trigger: 'Halal-friendly flag (Mindanao) · Family room · Kid-safe itinerary',
          pain: 'Không có peso pricing · Non-pork option không rõ ràng · Tour không phù hợp senior',
          booking: 'Traveloka · Klook · Facebook Group travel · 4–6 tuần trước',
          device: 'Mobile · GCash / bank transfer',
        },
        {
          id: 'beach-escape',
          tier: 'SECONDARY',
          name: 'Short-Haul Beach Escape',
          age: '25–45',
          size: 'Couple hoặc nhóm 3–5 người',
          share: 25,
          budget: '$500–1,200/người',
          motivation: 'Bali quá đắt (+30%) → VN Phú Quốc alternative · 4–7 ngày · Beach + snorkel',
          trigger: 'Cebu Pacific / PAL promo fare · Klook bundle flight+hotel+activity',
          pain: 'Không biết VN ngoài HCM · Guide không nói tiếng Tagalog/English rõ',
          booking: 'Klook PH · Traveloka · Agoda · 3–4 tuần trước',
          device: 'Mobile-first · GCash / credit card',
        },
      ],
      booking: {
        channels: [
          { name: 'Klook PH', role: 'PRIMARY', note: 'PH-native app · Peso pricing · GCash partner · Klook Points · Dominant channel' },
          { name: 'Facebook Messenger', role: 'PRIMARY', note: 'Discovery + closing channel · Auto-reply bắt buộc · Response ≤3h' },
          { name: 'Traveloka', role: 'SECONDARY', note: 'Flight+hotel bundle · SEA-native · Lớn cho family segment' },
          { name: 'Agoda', role: 'TERTIARY', note: 'Hotel-heavy · Activity secondary' },
          { name: 'Instagram DM', role: 'TERTIARY', note: 'Gen-Z barkada discover qua Reels · DM để hỏi giá' },
        ],
        leadTime: '3–5 tuần · Same-week booking phổ biến với flash sale',
        device: '90%+ mobile',
        payment: 'GCash · PayMaya · BDO bank transfer · Credit card',
        trigger: 'Flash sale Klook · Klook Points · Group package deal · Bali-alternative framing',
      },
      localization: [
        { lever: 'Ngôn ngữ', what: 'English native (PH) · Dùng idiom "barkada", "tropa" · Không cần dịch Tagalog' },
        { lever: 'Thanh toán', what: 'GCash · PayMaya · BDO bank transfer · Peso pricing niêm yết' },
        { lever: 'Thực phẩm', what: 'Halal-friendly flag cho Mindanao segment · Non-pork option rõ ràng · Moderate spice (PH food không cay)' },
        { lever: 'Lịch lễ', what: 'PH summer Apr–Jun · All Saints Nov 1 · Simbang Gabi Dec 16–24 · Sinulog Cebu đầu Jan' },
        { lever: 'Trust signal', what: 'FB Messenger response ≤3h · Video review từ PH creator · PH Tourism Board badge' },
        { lever: 'Social proof', what: 'Partner KOL PH Instagram (50K–200K followers) · TikTok Reels · Peso pricing visible' },
      ],
      opportunity: '~240K lượt/năm (+95% YoY) — Bali trade-down tạo demand bền vững. Klook PH flash sale 4x/năm là acquisition lever chính. Cruise pax ~10–12K Oct–Mar từ SG-homeport ships là upsell opportunity.',
      risk: 'Brand awareness thấp — PH traveler ít biết VN ngoài HCM + Phú Quốc. Booking cycle ngắn (same-week) gây khó khăn ops planning. Halal mis-labelling có thể gây backlash từ Mindanao segment.',
    },
    {
      id: 'uk', flag: '🇬🇧', name: 'Anh',
      demand7: 'TRUNG BÌNH',
      volume: '~300,000 lượt/năm',
      hasDetail: true,
      why7: 'Scotland + English schools out, gap year T7-T9',
      portrait: 'Hai nhóm chính: (1) couple 45–60 "đã đi Thái rồi" tìm substance văn hoá, thích small-group + slow travel; (2) gap-year 18–22 backpacker chi thấp, đi dài 4–6 tuần. Cả hai đều coi trọng review authentic, không tin marketing hoa mỹ.',
      budget: '$2,800–$5,800', leadTime: '8–10 tuần',
      party: '2 hoặc 1 người', visa: 'e-visa 90 ngày',
      favTours: ['hanoi-food-night', 'ha-giang-jeep', 'hue-imperial'],
      favOtas: ['gyg', 'viator'],
      peakMonths: [7, 8, 10, 11, 12],
      shoulderMonths: [4, 5, 9],
    },
    { id: 'fr', flag: '🇫🇷', name: 'Pháp', demand7: 'THẤP', favTours: ['sapa-trek', 'hue-imperial'], favOtas: ['direct'], budget: '$2,600–$4,800', leadTime: '10–12 tuần', placeholder: true, peakMonths: [3, 4, 10, 11] },
    { id: 'de', flag: '🇩🇪', name: 'Đức', demand7: 'THẤP', favTours: ['sapa-trek', 'cat-ba'], favOtas: ['gyg'], budget: '$2,400–$4,200', leadTime: '10–12 tuần', placeholder: true, peakMonths: [3, 9, 10, 11] },
    { id: 'kr', flag: '🇰🇷', name: 'Hàn', demand7: 'TRUNG BÌNH', favTours: ['bana-hills', 'nha-trang-spa'], favOtas: ['klook'], budget: '$800–$1,600', leadTime: '2–4 tuần', placeholder: true, peakMonths: [5, 6, 7, 8, 12] },
    { id: 'jp', flag: '🇯🇵', name: 'Nhật', demand7: 'THẤP', favTours: ['hue-imperial', 'hoi-an-wellness'], favOtas: ['direct'], budget: '$1,600–$3,000', leadTime: '6–8 tuần', placeholder: true, peakMonths: [3, 4, 10, 11] },
    { id: 'ru', flag: '🇷🇺', name: 'Nga', demand7: 'THẤP', favTours: ['nha-trang-spa'], favOtas: ['direct'], budget: '$1,400–$2,800', leadTime: '6–10 tuần', placeholder: true, peakMonths: [11, 12, 1, 2, 3] },
    { id: 'ca', flag: '🇨🇦', name: 'Canada', demand7: 'THẤP', favTours: ['india-halong', 'hanoi-food-night'], favOtas: ['viator'], budget: '$2,800–$5,500', leadTime: '6–10 tuần', placeholder: true, peakMonths: [1, 2, 12], shoulderMonths: [3, 11] },
    { id: 'nz', flag: '🇳🇿', name: 'New Zealand', demand7: 'THẤP', favTours: ['ha-giang-jeep', 'hoi-an-wellness'], favOtas: ['viator', 'gyg'], budget: '$2,500–$4,800', leadTime: '6–8 tuần', placeholder: true, peakMonths: [2, 3, 9, 10], shoulderMonths: [1, 4, 11] },
  ],

  otas: [
    {
      id: 'viator', name: 'Viator', parent: 'TripAdvisor company',
      share7: 40, commission: 25,
      hasDetail: true,
      stack: 'western',
      markets: ['us', 'uk', 'au'],
      strongTours: ['hanoi-food-night', 'hoi-an-wellness', 'ha-giang-jeep'],
      strongCategories: ['Food tours', 'Day cruise', 'Walking tours', 'Cultural'],
      peakMonths: [6, 7, 8, 12],
      note: 'Phí cao nhưng traffic lớn nhất thế giới — bắt buộc có listing. Listing title + hero image cần optimize theo mùa.',
      preTrip: 67, inDest: 33,
      paymentTerms: 'Net 30–45 ngày',
      boostOption: 'Viator Accelerate — tăng commission 1–2% để lên vị trí cao hơn',
      listingVolume: '~4,000–5,000 listings VN',
      listingTips: [
        'Hero image: 3:2 ratio, tối thiểu 1920×1280px, exposure chuẩn — ảnh tối sẽ bị rank thấp',
        'Title format: [Loại tour] + [Điểm đến] + [USP ngắn]. Ví dụ: "Hanoi Street Food Night Tour: Small Group, Local Guide"',
        'Description: 400–800 từ, dùng keyword tự nhiên trong 150 từ đầu (Google indexing)',
        'Upload tối thiểu 8–12 ảnh đa dạng: cảnh, người, food/detail',
        'Free cancellation policy = tăng conversion pre-trip đáng kể',
      ],
      algorithmSignals: [
        'Review count & velocity — tốc độ nhận review mới quan trọng hơn tổng số',
        'Conversion rate — tỷ lệ click-to-book; listing ảnh kém = drop thứ hạng',
        '"Bestseller" badge tự động gán khi đạt ngưỡng booking + rating',
        'Response time — operator trả lời inquiry nhanh được ưu tiên',
        'Completion rate — tour bị cancel nhiều sẽ bị phạt ranking',
      ],
      funnel: ['Google → "Vietnam tours"', 'TripAdvisor SEO', 'Viator listing', 'Review social proof', 'Book'],
      checklist: [
        { label: 'Upload đủ 10+ ảnh, đúng ratio 3:2, sáng đủ', freq: 'once' },
        { label: 'Bật Free Cancellation policy', freq: 'once' },
        { label: 'Đăng ký Viator Accelerate cho listing mới (bootstrap reviews)', freq: 'once' },
        { label: 'Cập nhật hero image theo mùa (T6–T8: hè; T11–T1: Tết/dry)', freq: 'seasonal' },
        { label: 'Reply tất cả reviews — kể cả 3 sao — trong 48h', freq: 'monthly' },
        { label: 'Kiểm tra conversion rate trong dashboard; dưới 3% cần đổi ảnh/title', freq: 'monthly' },
      ],
    },
    {
      id: 'gyg', name: 'GetYourGuide',
      share7: 25, commission: 20,
      hasDetail: true,
      stack: 'western',
      markets: ['uk', 'au', 'de', 'fr'],
      strongTours: ['ha-giang-jeep', 'sapa-trek', 'dalat-canyon'],
      strongCategories: ['Adventure', 'Walking', 'Day trip'],
      peakMonths: [6, 7, 8, 9, 10],
      note: 'Mạnh European market. UX app tốt hơn Viator. Yêu cầu chất lượng ảnh cao.',
      preTrip: 62, inDest: 38,
      paymentTerms: 'Net 30 ngày',
      boostOption: 'Sponsored placement (đang test)',
      listingVolume: '~2,000–3,000 listings VN',
      listingTips: [
        'Ảnh chất lượng cao hơn Viator — GYG editorial team review trước khi approve',
        'Title ngắn gọn, curated tone: "Ha Giang Loop: 3-Day Jeep Adventure"',
        'Structured description: What\'s included / What to expect / Meeting point rõ ràng',
        'Free cancellation 24h là tiêu chuẩn — không có sẽ bị rank thấp hơn',
        'GYG ưa "curated" hơn "breadth" — 1 listing chất lượng tốt hơn 5 listing trung bình',
      ],
      algorithmSignals: [
        'Review quality (không chỉ quantity) — GYG đọc nội dung review',
        'Photo score — system tự đánh giá brightness, composition của ảnh upload',
        'Cancellation rate thấp = ranking boost',
        'Listing completeness — điền đầy đủ 100% fields',
        'Response rate to customer messages trong 24h',
      ],
      funnel: ['Google → "things to do Vietnam"', 'GYG Direct / App', 'Filter theo category', 'Compare + Review', 'Book'],
      checklist: [
        { label: 'Submit ảnh đủ chất lượng cho GYG review (tránh bị reject)', freq: 'once' },
        { label: 'Điền 100% listing fields — không bỏ trống trường nào', freq: 'once' },
        { label: 'Set Free Cancellation 24h', freq: 'once' },
        { label: 'Optimize listing cho European peak (T6–T10): ảnh, title EN/DE/FR', freq: 'seasonal' },
        { label: 'Theo dõi photo score trong supplier dashboard', freq: 'monthly' },
      ],
    },
    {
      id: 'klook', name: 'Klook',
      share7: 20, commission: 18,
      hasDetail: true,
      stack: 'asian',
      markets: ['ph', 'kr', 'in'],
      strongTours: ['bana-hills', 'ph-barkada', 'phu-quoc-snorkel', 'saigon-vespa'],
      strongCategories: ['City half-day', 'Theme parks', 'Transfer', 'Cafe & photo spot'],
      peakMonths: [4, 5, 6, 7, 8],
      note: 'Tăng trưởng nhanh nhất (+21% traffic MoM). App-first, in-destination. Flash sale 4 lần/năm quan trọng hơn pricing thường ngày.',
      preTrip: 35, inDest: 65,
      paymentTerms: 'Net 30 ngày',
      boostOption: 'Flash sales, Klook Pass bundles, in-app promotions',
      listingVolume: '~500–800 listings VN',
      listingTips: [
        'Ảnh vuông 1:1 — mobile viewport nhỏ, hero image phải impactful ở 375px width',
        'Title ngắn, action-first: "Hà Nội Street Food Night" không cần dài dòng',
        'Video ngắn 30–60s trên listing tăng conversion đáng kể trên mobile',
        'Instant confirmation là bắt buộc — Klook users hay book same-day',
        'Chủ động đăng ký flash sale 4 lần/năm: giảm 15–25% trong 3–5 ngày',
      ],
      algorithmSignals: [
        'Instant confirmation enabled — không có sẽ không hiện trong filter',
        'Flash sale participation — sàn boost listing đang trong promotion',
        'Mobile click-through rate từ thumbnail',
        'Booking volume tích lũy trong 30 ngày gần nhất',
        'Klook Pass compatibility — thêm tour vào bundle tăng exposure',
      ],
      funnel: ['Social media (TikTok/Instagram)', 'Klook App search', 'Flash sale / Promo filter', 'Instant book'],
      checklist: [
        { label: 'Enable Instant Confirmation cho tất cả listing', freq: 'once' },
        { label: 'Upload video 30–60s (optional nhưng tăng CTR)', freq: 'once' },
        { label: 'Đăng ký flash sale T4 (PH summer), T6–T7 (peak), T11 (11.11), T12 (Giáng Sinh)', freq: 'seasonal' },
        { label: 'Kiểm tra listing trên mobile — zoom ảnh, đọc title ở màn 375px', freq: 'monthly' },
        { label: 'Negotiate commission nếu volume đạt >50 bookings/tháng', freq: 'once' },
      ],
    },
    {
      id: 'makemytrip', name: 'MakeMyTrip',
      share7: 10, commission: 15,
      hasDetail: true,
      stack: 'asian',
      markets: ['in'],
      strongTours: ['india-halong', 'bana-hills'],
      strongCategories: ['Family Halong', 'Multi-day package', 'Bundle flight+hotel+tour'],
      peakMonths: [5, 6, 7, 8, 12],
      note: 'Dominant India market — 70%+ India inbound bookings qua đây. Bundle flight+hotel+tour là format mặc định, không phải tour đơn lẻ.',
      preTrip: 80, inDest: 20,
      paymentTerms: 'Theo từng deal (varies)',
      boostOption: 'In-app promotions, featured listing',
      listingVolume: 'Không công khai',
      listingTips: [
        'Format bundle: flight + hotel + tour là default — listing tour đơn lẻ kém hiệu quả',
        'Cần options: Jain meal, vegetarian, guide tiếng Hindi hoặc English rõ ràng',
        'Payment: accept UPI, NetBanking — không phải chỉ credit card',
        'Family-first framing: nhấn "family-friendly", "kid-safe", "no steps"',
        'Giá niêm yết bằng INR (Rupee) dễ convert hơn cho khách Ấn',
      ],
      algorithmSignals: [
        'Package completeness — bundle đủ flight+hotel+tour rank cao hơn',
        'India-specific trust signals: rating, number of bookings từ Indian users',
        'Hindi/regional language support trong listing description',
        'Lead time — MakeMyTrip users book sớm (8–12 tuần trước); listing cần open availability xa',
        'Group size support — family group 6–10 người là norm',
      ],
      funnel: ['Google India → "Vietnam tour package"', 'MakeMyTrip → Holiday Packages', 'Bundle filter', 'EMI / UPI payment', 'Book'],
      checklist: [
        { label: 'Tạo bundle package: flight+hotel+tour (cùng partner agency nếu cần)', freq: 'once' },
        { label: 'Thêm Jain meal option và vegetarian option cho tất cả food activity', freq: 'once' },
        { label: 'Mở availability xa (tối thiểu 6 tháng tới) — Indian travelers book sớm', freq: 'monthly' },
        { label: 'Cập nhật mô tả family-friendly, kid-age-appropriate cho Halong + Bà Nà', freq: 'seasonal' },
        { label: 'Theo dõi INR pricing — rate fluctuation ảnh hưởng perceived value', freq: 'monthly' },
      ],
    },
    {
      id: 'direct', name: 'Direct',
      share7: 5, commission: 0,
      hasDetail: true,
      stack: 'both',
      markets: ['us', 'au', 'vn-diaspora'],
      strongTours: ['pu-luong', 'con-dao', 'quy-nhon', 'ha-giang-jeep'],
      strongCategories: ['Premium', 'Custom itinerary', 'Repeat client', 'Referral'],
      peakMonths: [10, 11, 12, 1],
      note: 'Zero commission, margin cao nhất. 60%+ là repeat/referral. Chi phí acquisition cao nhưng LTV vượt trội mọi sàn.',
      preTrip: 88, inDest: 12,
      paymentTerms: 'Nhận ngay khi book (bank transfer / Wise)',
      boostOption: 'SEO, email marketing, referral program',
      listingVolume: 'N/A — kênh tự owned',
      listingTips: [
        'Website cần SEO: target "Vietnam private tour", "Ha Giang jeep tour 2026"',
        'Email list là tài sản quan trọng nhất — capture email mọi khách từng đi',
        'Referral program: tặng $25–$50 credit cho khách giới thiệu thành công',
        'WhatsApp / Zalo response trong 2h tăng conversion đáng kể',
        '"Best rate guarantee" — cam kết giá direct thấp hơn OTA (sau khi trừ commission)',
      ],
      algorithmSignals: [
        'Google SEO rank cho long-tail keywords ("private tour Vietnam 2026")',
        'Google My Business rating — hiện ngay trong local search',
        'TripAdvisor reviews (dù không book qua đó) tăng trust cho direct',
        'Email open rate & repeat booking rate',
        'Referral conversion — % khách cũ giới thiệu khách mới',
      ],
      funnel: ['Word of mouth / Referral', 'Google SEO / GMB', 'Operator website', 'WhatsApp / Zalo', 'Bank transfer'],
      checklist: [
        { label: 'Setup Google My Business với ảnh, giờ, phone number đầy đủ', freq: 'once' },
        { label: 'Cài email capture sau mỗi tour hoàn thành (form hoặc guide nhắc)', freq: 'once' },
        { label: 'Launch referral program: $25 credit cho người giới thiệu', freq: 'once' },
        { label: 'Gửi email "Vietnam 2026 highlights" cho list vào T9–T10 (pre-peak booking window)', freq: 'seasonal' },
        { label: 'Publish 1 SEO blog/tháng: "Ha Giang road conditions T7", "Best Vietnam tours from Australia"', freq: 'monthly' },
        { label: 'Reply mọi Google review trong 24h', freq: 'monthly' },
      ],
    },
  ],
};
